### ISSUE TITLE
fire-incidents.zip is missing from Section 4 files

### ISSUE THREAD

**Issue by stan-t** [PacktPublishing/Apache-Spark-3-for-Data-Engineering-and-Analytics-with-Python-#1]

**Comment by Sonakshis** [comment]
Hi 
Thank you so much for bringing this to our attention! We have updated the repository.
https://github.com/PacktPublishing/Apache-Spark-3-for-Data-Engineering-and-Analytics-with-Python-/blob/35da4db8a4101a4f34f609d0cbbef12b316955b5/Section%204%20Resources/fire-incidents.zip
